app/suppliers/__init__.py
from flask.blueprints import Blueprint 

suppliers_bp = Blueprint('suppliers', __name__, static_folder="static", template_folder='templates', url_prefix='/suppliers')

import app.suppliers.routes

app/suppliers/routes.py
from app.suppliers import suppliers_bp
from flask import render_template, redirect, url_for, request, jsonify
from flask_login import current_user, login_required
from werkzeug import exceptions
from app.models import User, Products, Suppliers, Suppliers_Products
from app.extentions import db
from sqlalchemy.exc import IntegrityError
import uuid


class NotAuthorized(exceptions.HTTPException):
    code = 405 
    description = 'User is not authorized to perform this action'

class ProductNOTExist(exceptions.HTTPException):
    code = 404
    description = 'Product dose not exist.'

class SupplierNOTExist(exceptions.HTTPException):
    code = 404
    description = 'Supplier dose not exist.'

class SupplierAlreadyExist(exceptions.HTTPException):
    code = 400
    description = 'Supplier dose already exist.'

@suppliers_bp.errorhandler(exceptions.HTTPException)
def handle_error(e):
    return e.description, e.code

suppliers_bp.register_error_handler(SupplierNOTExist, handle_error)
suppliers_bp.register_error_handler(SupplierAlreadyExist, handle_error)
suppliers_bp.register_error_handler(NotAuthorized, handle_error)
suppliers_bp.register_error_handler(ProductNOTExist, handle_error)


### USER ENDPOINTS

@suppliers_bp.route('/all', methods=['GET'])
@login_required
def all():
    suppliers = Suppliers.query.all()
    suppliers_json = []
    for supplier in suppliers:
        supplier_json = supplier.to_dict()
        supplier_json["s_p"] = []
        s_ps = Suppliers_Products.query.filter(Suppliers_Products.supplier_public_id==supplier.public_id).all()
        for s_p in s_ps:
            json_s_p = s_p.to_dict()
            product = Products.query.filter(Products.public_id==s_p.product_public_id).first()
            json_s_p["product"] = product.to_dict()
            supplier_json["s_p"].append(json_s_p)
        suppliers_json.append(supplier_json)
        
    return render_template("suppliers.html", user=current_user, suppliers=suppliers_json)


@suppliers_bp.route('/<public_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(public_id):
    if request.method == 'GET':
        supplier = Suppliers.query.filter_by(public_id=public_id).first()
        return render_template("suppliers_edit.html", user=current_user, supplier=supplier)
    else:
        edit_supplier(public_id)
        return redirect(url_for('suppliers.all'))

@suppliers_bp.route('/<public_id>/delete', methods=['GET', 'POST'])
@login_required
def delete(public_id):
    if request.method == 'GET':
        supplier = Suppliers.query.filter_by(public_id=public_id).first()
        return render_template("suppliers_delete.html", user=current_user, supplier=supplier)
    else:
        delete_supplier(public_id)
        return redirect(url_for('suppliers.all'))
    
@suppliers_bp.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    if request.method == 'GET':
        return render_template("suppliers_create.html", user=current_user)
    else:
        create_supplier()
        return redirect(url_for('suppliers.all'))
    
@suppliers_bp.route('/<public_id>/products/add', methods=['GET', 'POST'])
@login_required
def products_add(public_id):
    if request.method == 'GET':
        supplier = Suppliers.query.filter_by(public_id=public_id).first()
        products = Products.query.all()
        return render_template("suppliers_create_s_p.html", user=current_user, supplier=supplier, products=products)
    else:
        add_product_to_supplier(public_id)
        return redirect(url_for('suppliers.all', public_id=public_id))
    
@suppliers_bp.route('/<public_id>/products/<s_p_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_product(public_id, s_p_id):
    if request.method == 'GET':
        supplier = Suppliers.query.filter_by(public_id=public_id).first()
        s_p = Suppliers_Products.query.filter_by(public_id=s_p_id).first()
        product = Products.query.filter_by(public_id=s_p.product_public_id).first()
        return render_template("suppliers_delete_s_p.html", user=current_user, supplier=supplier, s_p=s_p, product=product)
    else:
        delete_product_to_supplier(public_id, s_p_id)
        return redirect(url_for('suppliers.all', public_id=public_id))


### API ENDPOINTS

# ------------------------------------------- SUPPLIER ---------------------------------------------------

    
@suppliers_bp.route('/', methods=['GET'])
def get_suppliers():
    suppliers = Suppliers.query.all()
    supp_list = [] 
    for supp in suppliers:
        supp_list.append(supp.to_dict())
    return jsonify(supp_list)



# ------------------------------------------- SUPPLIER RESSOURCE ---------------------------------------------------
# CREATE:
@suppliers_bp.route('/', methods=['POST'])
@login_required
def create_supplier():
    if current_user.user_type != 1:
        raise NotAuthorized()
    public_id = str(uuid.uuid4())
    title = request.form["title"]
    
    try:
        supp = Suppliers(public_id=public_id, title=title)
        db.session.add(supp)
        db.session.commit()
    except IntegrityError:
        raise SupplierAlreadyExist()
    
    return supp.to_dict()

@suppliers_bp.route('/<public_id>', methods=['GET'])
def get_supplier(public_id):
    supplier = Suppliers.query.filter(Suppliers.public_id == public_id).first()
    if not supplier:
        raise SupplierNOTExist()
    return jsonify(supplier.to_dict())


@suppliers_bp.route('/<public_id>', methods=['PUT'])
@login_required
def edit_supplier(public_id):
    if current_user.user_type != 1:
        raise NotAuthorized()
    supp = Suppliers.query.filter(Suppliers.public_id == public_id).first()
    if not supp:
        raise SupplierNOTExist()
    # TODO: if forms are not given
    title = request.form["title"]
    supp.title = title
    db.session.commit()
    return jsonify(supp.to_dict())

@suppliers_bp.route('/<public_id>', methods=['DELETE'])
@login_required
def delete_supplier(public_id):
    if current_user.user_type != 1:
        raise NotAuthorized()
    supplier = Suppliers.query.filter(Suppliers.public_id == public_id).first()
    if not supplier:
        raise SupplierNOTExist()
    db.session.delete(supplier)
    db.session.commit()
    return jsonify(supplier.to_dict())


# SUPPLIERS PRODUCTS

@suppliers_bp.route('/<public_id>/product/add', methods=['PUT'])
@login_required
def add_product_to_supplier(public_id):
    if current_user.user_type != 1:
        raise NotAuthorized()
    supplier = Suppliers.query.filter(Suppliers.public_id == public_id).first()
    if not supplier:
        raise SupplierNOTExist()
    product_id = request.form["product_id"]
    product = Products.query.filter(Products.public_id == product_id).first()
    if not product:
        raise ProductNOTExist()
    s_p = Suppliers_Products(supplier_public_id=supplier.public_id, product_public_id=product.public_id)
    db.session.add(s_p)
    db.session.commit()
    return jsonify(s_p.to_dict())

@suppliers_bp.route('/<public_id>/product/<s_p_id>', methods=['DELETE'])
@login_required
def delete_product_to_supplier(public_id, s_p_id):
    print(public_id, s_p_id)
    if current_user.user_type != 1:
        raise NotAuthorized()
    supplier = Suppliers.query.filter(Suppliers.public_id == public_id).first()
    if not supplier:
        raise SupplierNOTExist()
    s_p = Suppliers_Products.query.filter(Suppliers_Products.public_id == s_p_id).first()
    if not s_p:
        raise ProductNOTExist()
    db.session.delete(s_p)
    db.session.commit()
    return jsonify(s_p.to_dict())

app/suppliers/templates/suppliers.html
{% extends "base.html" %}

{% block content %}

<link rel= "stylesheet" type= "text/css" href= "{{ url_for('suppliers.static',filename='styles/suppliers.css') }}">

<a href="{{ url_for('suppliers.all') }}" class="title is-3">Suppliers:</a>
<div class="columns is-8 is-multiline">
    {% for supplier in suppliers %}
        <div class="column is-one-quarter">
            <div class="card product_container">
                <div class="card-content">
                    <div class="media-content">
                        <p class="title is-4 has-text-dark">{{supplier.title}}</p>
                    </div>
                    <nav class="panel">
                        <p class="panel-heading">Products</p>
                        {% for s_p in supplier.s_p %}
                            <div class="panel-block is-active">
                                <a href="{{ url_for('suppliers.delete_product', public_id=supplier.public_id, s_p_id=s_p.public_id) }}" class="delete"></a> <div style="width:1rem"></div> <div class="name">{{s_p.product.title}}</div>
                            </div>
                            
                        {% endfor %}
                        <a href="{{ url_for('suppliers.products_add', public_id=supplier.public_id) }}" class="panel-block is-active">
                            <span class="panel-icon">
                            ➕
                        </a>
                    </nav>
                </div>
                <footer class="card-footer">
                    <a href="{{ url_for('suppliers.edit', public_id=supplier.public_id) }}" class="card-footer-item">🖊️</a>
                    <a href="{{ url_for('suppliers.delete', public_id=supplier.public_id) }}" class="card-footer-item">🗑️</a>
                </footer>
            </div>
        </div>
    {% endfor %}
    <div class="column is-one-quarter">
        <div class="card product_container">
            <div class="card-content">
                <div class="media-content">
                    <p class="title is-4 has-text-dark">CREATE NEW SUPPLIER</p>
                </div>
            </div>
            <footer class="card-footer">
                <a href="{{ url_for('suppliers.create') }}" class="card-footer-item">➕</a>
            </footer>
        </div>
    </div>
</div>

{% endblock %}

app/suppliers/templates/suppliers_create.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Create Supplier</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="{{ url_for('suppliers.create') }}">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="title" placeholder="Title" autofocus="">
                </div>
            </div>

            
            <button class="button is-block is-info is-large is-fullwidth">Create</button>
        </form>
    </div>
</div>
{% endblock %}

app/suppliers/templates/suppliers_create_s_p.html
{% extends "base.html" %}

{% block content %}

<div class="column is-4 is-offset-4">
    <h3 class="title">Add Product for '{{supplier.title}}'</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="{{ url_for('suppliers.products_add', public_id=supplier.public_id) }}">
            <select name="product_id" class="selectpicker form-control input is-large">
                {% for product in products %}
                    <option value="{{ product.public_id }}">{{product.title}}</option>
                {% endfor %}
            </select>
            
            <button class="button is-block is-info is-large is-fullwidth">Create</button>
        </form>
    </div>
</div>
{% endblock %}

app/suppliers/templates/suppliers_delete.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Edit Supplier</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="{{ url_for('suppliers.delete', public_id=supplier.public_id) }}">
            Are You sure about deleting '{{supplier.title}}'?
            
            <button class="button is-block is-danger is-large is-fullwidth">Yes, Delete</button>
        </form>
    </div>
</div>
{% endblock %}

app/suppliers/templates/suppliers_delete_s_p.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Delete Product for Supplier</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="{{ url_for('suppliers.delete_product', public_id=supplier.public_id, s_p_id=s_p.public_id) }}">
            Are You sure about deleting '{{product.title}}' for '{{supplier.title}}'?
            
            <button class="button is-block is-danger is-large is-fullwidth">Yes, Delete</button>
        </form>
    </div>
</div>
{% endblock %}

app/suppliers/templates/suppliers_edit.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Edit Supplier</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="{{ url_for('suppliers.edit', public_id=supplier.public_id) }}">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="title" placeholder="Title" autofocus="" value="{{supplier.title}}">
                </div>
            </div>

            
            <button class="button is-block is-info is-large is-fullwidth">Save</button>
        </form>
    </div>
</div>
{% endblock %}